### ISSUE TITLE
MAXITER

### ISSUE THREAD

**Issue by abhi2610** [quantombone/exemplarsvm#17]
MAXITER is assigned in the mining_parameters, but it seems that it is not used being used in the training process as an upper cap of iterations. I just saw that even if my upper limit was 10 for iterations, I had mat files from 25-30th iterations.

I even couldn't find a check using MAXITER in train_all_exemplars. Though an an easy fix, but am I missing something?

**Comment by quantombone** [comment]
I renamed MAXITER to MAX_MINE_ITERATIONS, because these parameters aren't always used for mining.  When not used for mining, MAXITER is too vague.  I also added the check for finishing mining.
Now mining finishes when one of these things happens:
- the mining queue is empty
- MAX_MINE_ITERATIONS performed
- MAX_TOTAL_MINED_IMAGES mined
